name: alm
description: A Dart lib, Cool? Try use.
version: 0.0.5
homepage: https://gitee.com/darto/alm

## pub publish --server=https://pub.dartlang.org

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  convert: ^2.1.1
  crypto: ^2.1.5
